monkeysApp/models.py
from sqlalchemy import SmallInteger, Integer, String, Column, ForeignKey, select
from sqlalchemy.schema import Table
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, backref
from monkeysApp.app import DbSession as db


class BaseModel(object):
    query = db.query_property()

    def as_dict(self):
        return {c.name: getattr(self, c.name) for c in self.__table__.columns}


Base = declarative_base(cls=BaseModel)

friendships = Table('friendships',
                    Base.metadata,
                    Column('user_id', Integer, ForeignKey('monkey.id')),
                    Column('friend_id', Integer, ForeignKey('monkey.id'))
)

monkey_friend_requests = Table('friend_requests',
                               Base.metadata,
                               Column('user_id', Integer, ForeignKey('monkey.id')),
                               Column('requester_id', Integer, ForeignKey('monkey.id'))
)


class Monkey(Base):
    """Monkey model"""
    __tablename__ = "monkey"

    id = Column(Integer, primary_key=True)
    email = Column(String(256), unique=True)
    name = Column(String(256))
    age = Column(Integer)
    password = Column(String(256))
    face_image = Column(String(256))
    admin = Column(SmallInteger, default=0)

    friends = relationship('Monkey',
                           secondary=friendships,
                           primaryjoin=(friendships.c.user_id == id),
                           secondaryjoin=(friendships.c.friend_id == id),
                           backref=backref('friendships', lazy='dynamic'),
                           lazy='dynamic')

    friend_requests = relationship('Monkey',
                                   secondary=monkey_friend_requests,
                                   primaryjoin=(monkey_friend_requests.c.user_id == id),
                                   secondaryjoin=(monkey_friend_requests.c.requester_id == id),
                                   backref=backref('monkey_friend_requests', lazy='dynamic'),
                                   lazy='dynamic')


    def __init__(self, email='', name='', age='', password=''):
        self.email = email
        self.name = name
        self.age = age
        self.password = password

    def has_friend_request(self, other_monkey):
        return other_monkey in self.friend_requests

    def request(self, other_monkey):
        if (not other_monkey in self.friend_requests) and (not self in other_monkey.friend_requests):
            self.friend_requests.append(other_monkey)

    def friend_requests_count(self):
        return self.friend_requests.count()

    def friend(self, monkey):
        """
            Make a friend monkey
            :param monkey to be friended
            :return True if friending succeeded, False otherwise
        """
        if monkey.id != self.id:
            # Check if they are already friends
            if not self.is_friend(monkey):
                # Check if the other user has sent friend request
                if monkey in self.friend_requests:
                    # Accept the friendship
                    self.friends.append(monkey)
                    # Remove the old friend request
                    self.friend_requests.remove(monkey)
                    # Initiate friend request
                else:
                    monkey.request(self)
                return True
            else:
                return False
        else:
            return False

    def deny_request(self, monkey):
        """
            Deny the friend request
            :param monkey: monkey to deny request from
            :return:
        """
        if monkey in self.friend_requests:
            self.friend_requests.remove(monkey)

    def is_friend(self, monkey):
        """
            Check if monkey is the friend of this
            :param monkey: the monkey to check against
            :return: True if friends
        """
        if (monkey in self.friends) or (self in monkey.friends):
            return True
        return False

    def is_admin(self):
        return self.admin == 1

    def remove_friend(self, monkey):
        if monkey in self.friends:
            self.friends.remove(monkey)
        if self in monkey.friends:
            monkey.friends.remove(self)

    def is_anonymous(self):
        return False

    def is_authenticated(self):
        return True

    def get_id(self):
        return unicode(self.id)

    def __repr__(self):
        return self.__str__()

    def __str__(self):
        return u'<{} {} {} {}>'.format(self.id, self.email, self.name,
                                       self.age)


friendship_union = select([
    friendships.c.friend_id,
    friendships.c.user_id
]).union(
    select([
        friendships.c.user_id,
        friendships.c.friend_id]
    )
).alias()

Monkey.all_friends = relationship('Monkey',
                                  secondary=friendship_union,
                                  primaryjoin=(Monkey.id == friendship_union.c.friend_id),
                                  secondaryjoin=(Monkey.id == friendship_union.c.user_id),
                                  viewonly=True)

monkeysApp/forms.py
__author__ = 'janiniem'

from flask.ext.wtf import Form
from wtforms import TextField, PasswordField, IntegerField
from wtforms.validators import Required, Email


class LoginForm(Form):
    login_name = TextField('Login', [Required()])
    password = PasswordField('Password', [Required()])


class MonkeyForm(Form):
    email = TextField('Email', validators=[Required(), Email(message=u'Invalid email address.')])
    name = TextField('Name', validators=[Required()])
    age = IntegerField('Age', validators=[Required()])
    password = PasswordField('Password')

monkeysApp/app.py
from __future__ import absolute_import

from flask import Flask, _app_ctx_stack, abort
from flask.ext.login import LoginManager
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, scoped_session, Query as SAQuery
from sqlalchemy.orm.exc import NoResultFound, MultipleResultsFound


DbSession = scoped_session(sessionmaker(),
                           # __ident_func__ should be hashable, therefore used
                           # for recognizing different incoming requests
                           scopefunc=_app_ctx_stack.__ident_func__)

login_manager = LoginManager()


class BaseQuery(SAQuery):
    """
    Extended SQLAlchemy Query class, provides :meth:`BaseQuery.first_or_404`
    and :meth:`BaseQuery.get_or_404` similarily to Flask-SQLAlchemy.
    These methods are additional, :class:`BaseQuery` works like a normal
    SQLAlchemy query class.
    """

    def get_or_404(self, identity):
        result = self.get(identity)
        if result is None:
            abort(404)
        return result

    def first_or_404(self):
        result = self.first()
        if result is None:
            abort(404)
        return result


def create_app(name, config_obj):
    app = Flask(name, template_folder="monkeysApp/templates", static_folder="monkeysApp/static")
    app.config.from_object(config_obj)

    app.engine = create_engine(app.config["SQLALCHEMY_DATABASE_URI"])

    global DbSession
    DbSession.configure(bind=app.engine, query_cls=BaseQuery)

    @app.teardown_appcontext
    def teardown(exception=None):
        if isinstance(exception, NoResultFound) or \
                isinstance(exception, MultipleResultsFound):
            abort(404)
        global DbSession
        if DbSession:
            DbSession.remove()

    register_extensions(app)
    register_blueprints(app)

    return app


def register_extensions(app):
    global login_manager
    login_manager.init_app(app)
    login_manager.login_view = 'main_blueprint.login'


import monkeysApp.views.main


def register_blueprints(app):
    app.register_blueprint(monkeysApp.views.main.main_blueprint)
    return None

monkeysApp/views/main.py
import random

from flask import Blueprint, g, render_template, request, flash, redirect, url_for, session, make_response
from flask.ext.login import current_user, login_required, logout_user

from sqlalchemy.exc import IntegrityError

from ..app import login_manager, DbSession as db
from ..models import Monkey
from ..forms import MonkeyForm, LoginForm

main_blueprint = Blueprint('main_blueprint', __name__, template_folder='../templates')


@login_manager.user_loader
def load_user(user_id):
    return Monkey.query.get(int(user_id))


@main_blueprint.before_request
def before_request():
    g.user = current_user


@main_blueprint.route('/', methods=['GET'])
@login_required
def index():
    """Browse user profiles"""
    page_title = "Browse profiles"
    monkeys = Monkey.query.all()
    return render_template('monkeys.html', page_title=page_title, profiles=monkeys)


@main_blueprint.route('/monkeys/add', methods=['GET', 'POST'])
@login_required
def monkey_add():
    """
    Add new monkey to database
    """
    if g.user.is_admin() != 1:
        flash('You are not allowed in here!')
        return redirect(url_for('main_blueprint.index'))

    form = MonkeyForm(request.form)
    page_title = "Add monkey"

    random_face = ['trollface.png', '9.jpg', 'monkey.png']

    if request.method == 'POST' and form.validate_on_submit():
        monkey = Monkey()
        face_num = random.randint(0, len(random_face) - 1)
        monkey.face_image = random_face[face_num]
        form.populate_obj(monkey)
        try:
            db.add(monkey)
            db.commit()

        except IntegrityError, exc:
            reason = exc.message
            if reason.find('unique constraint'):
                flash('Email already in use, please use another email address!')
                db.rollback()
                return redirect(url_for('main_blueprint.monkey_add'))
        flash('New monkey added successfully')
        return redirect(url_for('main_blueprint.monkey_add'))
    return render_template('monkey_form.html', form_action='/monkeys/add', form=form, page_title=page_title, form_edit=False)


@main_blueprint.route('/monkeys/friends', methods=['GET'])
@login_required
def monkey_friends():
    """Show list of friends of g.user"""
    page_title = "Your friends"
    me = g.user
    friends = me.all_friends
    return render_template('monkey_friends.html', friends=friends, page_title=page_title)


@main_blueprint.route('/monkeys/friend_requests', methods=['GET'])
@login_required
def monkey_friend_requests():
    """Get the list of pending friend requests"""
    page_title = "Friend requests"
    me = g.user
    frqs = me.friend_requests.all()
    return render_template('friend_requests.html', page_title=page_title, friend_requests=list(frqs))


@main_blueprint.route('/monkeys/profile', methods=['GET', 'POST'])
@login_required
def monkey_my_profile():
    """Get the profile of logged in user"""
    page_title = "Your profile"
    me = g.user

    form = MonkeyForm(request.form, obj=me)
    if form.validate_on_submit() and request.method == 'POST':
        monkey = Monkey.query.get(me.id)
        form.populate_obj(monkey)
        db.commit()
        return redirect(url_for('main_blueprint.monkey_my_profile'))

        return render_template('monkey_form.html', page_title=page_title, form=form, my_profile=True, monkey=me)
    return render_template('monkey_form.html', page_title=page_title, form=form, my_profile=True, monkey=me, form_edit=True)


@main_blueprint.route('/monkeys/profile/<int:monkey_id>', methods=['GET'])
@login_required
def monkey_show_profile(monkey_id):
    """Show profile with monkey id"""
    me = g.user
    monkey = Monkey.query.get(monkey_id)
    is_my_friend = monkey.is_friend(me)
    sent_friend_request = monkey.has_friend_request(me)
    rcvd_friend_request = me.has_friend_request(monkey)
    my_profile = False

    if me.id == monkey.id:
        my_profile = True

    if monkey is not None:
        return render_template('monkey_profile.html',
                               page_title=monkey.name,
                               my_profile=my_profile,
                               is_my_friend=is_my_friend,
                               profile=monkey,
                               sent_friend_request=sent_friend_request,
                               rcvd_friend_request=rcvd_friend_request)


@main_blueprint.route('/monkeys/remove_friend/<int:monkey_id>', methods=['GET'])
@login_required
def remove_friend(monkey_id):
    """Unfriend monkey"""
    me = g.user
    monkey = Monkey.query.filter_by(id=monkey_id).first()
    if monkey is not None:
        me.remove_friend(monkey)
        db.commit()
        return make_response("", 200)
    else:
        return make_response("", 400)


@main_blueprint.route('/monkeys/make_friend/<int:monkey_id>', methods=['GET'])
@login_required
def make_friend(monkey_id):
    """Be friends with monkey"""
    send_to = Monkey.query.filter_by(id=monkey_id).first()
    if send_to is not None:
        me = g.user
        if me.friend(send_to) is not False:
            db.commit()
            response = make_response("", 200)
        else:
            response = make_response("", 400)
        return response
    else:
        response = make_response("", 400)
        return response


@main_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    """Login with user email and password"""
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = Monkey.query.filter_by(email=form.login_name.data).first()
        if user and (user.password == form.password.data):
            session['user_id'] = user.id
            flash('Welcome %s' % user.email)
            return redirect(url_for('main_blueprint.index'))
        flash('Wrong email or password', 'error-message')
    return render_template('login.html', form=form)


@main_blueprint.route('/logout')
@login_required
def logout():
    """Logout currently authenticated user"""
    if g.user is not None:
        logout_user()
        flash('You were logged out')
        return redirect(url_for('main_blueprint.login'))

monkeysApp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Meet Monkeys</title>

    <!-- Bootstrap Core CSS - Uses Bootswatch Flatly Theme: http://bootswatch.com/flatly/ -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/css/freelancer.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/static/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet"
          type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top" class="index">

<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#page-top">Meet Monkeys</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li class="hidden">
                    <a href="#page-top"></a>
                </li>
                <li class="page-scroll">
                    <a href="{{ url_for('main_blueprint.index') }}">Browse</a>
                </li>
                <li class="page-scroll">
                    <a href="{{ url_for('main_blueprint.monkey_friends') }}">Friends</a>
                </li>
                <li class="page-scroll">
                    <a href="{{ url_for('main_blueprint.monkey_my_profile') }}">My profile</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>
<!-- Header -->
<header>
    {% block header_content %}
    {% endblock %}
</header>

{% block content %}
{% endblock %}

<!-- jQuery -->
<script src="/static/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="/static/js/bootstrap.min.js"></script>

<!-- Plugin JavaScript -->
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
<script src="/static/js/classie.js"></script>
<script src="/static/js/cbpAnimatedHeader.js"></script>
<script src="/static/js/friend_button.js"></script>

<!-- Contact Form JavaScript -->
<script src="/static/js/jqBootstrapValidation.js"></script>
<script src="/static/js/forms.js"></script>
<!-- Custom Theme JavaScript -->
<script src="/static/js/freelancer.js"></script>

</body>
</html>

monkeysApp/templates/friend_requests.html
{% extends 'base.html' %}
{% block header_content %}
        {% include 'header.html' %}
{% endblock %}
{% block content %}
    <ul>
                {% for friend_request in friend_requests %}
                <li>{{ friend_request.name }}</li>
                {% else %}
                <p> No friend requests. </p>
                {% endfor %}
    </ul>
{% endblock %}

monkeysApp/templates/header.html
{% block header_content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2>{{ page_title }}</h2>
                <hr class="star-light">
            </div>
        </div>
    </div>
{% endblock %}

monkeysApp/templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link href="/static/css/bootstrap.css" rel="stylesheet" media="screen">
    <script src="/static/js/jquery-1.11.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <title>Sign in</title>

    <!-- Custom styles for this template -->
    <link href="/static/css/signin.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="container">

      <form class="form-signin" action="/login" method="POST">
        {{ form.csrf_token }}
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="text" class="form-control" id="login_name" name="login_name" placeholder="Login name" autofocus>
        <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        <button class="btn btn-primary btn-block" type="submit">Sign in</button>
      </form>

    </div> <!-- /container -->
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <ul>
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

monkeysApp/templates/monkey_form.html
{% extends 'base.html' %}
{% block header_content %}
        {% include 'header.html' %}
{% endblock %}
{% block content %}
    <section id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <!-- To configure the contact form email address, go to mail/contact_me.php and update the email address in the PHP file on line 19. -->
                    <!-- The form should work on most web servers, but if the form is not working you may need to configure your web server differently. -->
                    <form class="form" action="{{ form_action }}" method="post" name="sentMessage" id="contactForm" novalidate>
                        {{ form.csrf_token }}
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Name</label>
                                {{ form.name(class='form-control', placeholder='Name', id='name', **{'data-validation-required-message':'Please enter your name.'}) }}
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Email Address (login name)</label>
                                {% if form_edit %}
                                    {{ form.email(readonly="readonly", class='form-control', placeholder='Email', id='email', **{'data-validation-required-message':'Please enter your email.'}) }}
                                {% else %}
                                    {{ form.email(class='form-control', placeholder='Email', id='email', **{'data-validation-required-message':'Please enter email address.'}) }}
                                {% endif %}
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Age</label>
                                {{ form.age(class='form-control', placeholder='Age', id='age', **{'data-validation-required-message':'Please enter your age.'}) }}
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Password</label>
                                {{ form.password(required='true', class='form-control', placeholder='Password', id='password') }}
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
                        <div class="row control-group">
                            <div class="form-group col-xs-12 floating-label-form-group controls">
                                <label>Retype password</label>
                                <input type="password" class="form-control" placeholder="Confirm Password" name="confirmPassword" data-validation-matches-match="password" data-validation-matches-message="Must match password entered above">
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>

                        <br>
                        <div id="success"></div>
                        <div class="row">
                            <div class="form-group col-xs-12">
                                <button type="submit" class="btn btn-success btn-lg">Save</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

monkeysApp/templates/monkey_friends.html
{% extends 'base.html' %}
{% block header_content %}
        {% include 'header.html' %}
{% endblock %}
{% block content %}
    <section id="portfolio">
        <div class="container">
            <div class="row">
                {% for friend in friends %}
                <div class="col-sm-4 portfolio-item">
                    <a href="{{ url_for('main_blueprint.monkey_show_profile', monkey_id=friend.id) }}" class="portfolio-link" data-toggle="modal">
                        <div class="caption">

                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                                <p>{{ friend.name }}</p>

                            </div>
                        </div>
                        <img src="/static/img/profile/cabin.png" class="img-responsive" alt="">
                    </a>
                </div>
                {% else %}
                <h3>You currently have no friends!</h3>
                {% endfor %}
            </div>
        </div>
    </section>

{% endblock %}
        <!--
                <section id="profiles">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Profiles</h2>
                    <hr class="star-primary">
                </div>
            </div>
            <div class="row">
                <div class="col-sm-4 portfolio-item">
                    <a href="#portfolioModal1" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="/static/img/profile/cabin.png" class="img-responsive" alt="">
                    </a>
                </div>
                <div class="col-sm-4 portfolio-item">
                    <a href="#portfolioModal2" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="/static/img/profile/cake.png" class="img-responsive" alt="">
                    </a>
                </div>
                <div class="col-sm-4 portfolio-item">
                    <a href="#portfolioModal3" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="/static/img/profile/circus.png" class="img-responsive" alt="">
                    </a>
                </div>
                <div class="col-sm-4 portfolio-item">
                    <a href="#portfolioModal4" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="/static/img/profile/game.png" class="img-responsive" alt="">
                    </a>
                </div>
                <div class="col-sm-4 portfolio-item">
                    <a href="#portfolioModal5" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="/static/img/profile/safe.png" class="img-responsive" alt="">
                    </a>
                </div>
                <div class="col-sm-4 portfolio-item">
                    <a href="#portfolioModal6" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                            </div>
                        </div>
                        <img src="/static/img/profile/submarine.png" class="img-responsive" alt="">
                    </a>
                </div>
            </div>
        </div>
    </section>-->

monkeysApp/templates/monkey_profile.html
{% extends 'base.html' %}
{% block header_content %}
        {% include 'profile_header.html' %}
{% endblock %}
    {% block content %}
        <section id="about">
        </section>
    {% endblock %}

monkeysApp/templates/monkeys.html
{% extends 'base.html' %}
    {% block header_content %}
        {% include 'header.html' %}
    {% endblock %}
    {% block content %}

    <!-- Profiles -->
    <section id="portfolio">
        <div class="container">
            <div class="row">
                {% for profile in profiles %}
                <div class="col-sm-4 portfolio-item">
                    <a href="{{ url_for('main_blueprint.monkey_show_profile', monkey_id=profile.id) }}" class="portfolio-link" data-toggle="modal">
                        <div class="caption">
                            <div class="caption-content">
                                <i class="fa fa-search-plus fa-3x"></i>
                                <p>{{ profile.name }}</p>
                            </div>
                        </div>
                        <div class="user-photo horizontal-center vertical-center">
                        <img src="/static/img/profile/{{ profile.face_image }}" class="img-responsive" alt="">
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endblock %}